# version format
version: 1.0.{build}

# Build worker image (VM template)
image: Visual Studio 2022

build: off
platform:
  - x64

# branches to build
branches:
  # whitelist
  only:
    - main
    - testing
    
  # blacklist
  except:
    - gh-pages

# Do not build on tags (GitHub, Bitbucket, GitLab, Gitea)
skip_tags: true


# Skipping commits affecting specific files (GitHub only). More details here: /docs/appveyor-yml
skip_commits:
 files:
   - docs/*

# Maximum number of concurrent jobs for the project
max_jobs: 1

# set clone depth
clone_depth: 3                      


install:
  # run the powershell script, note .\
  - ps: .\rakudo.ps1
  
# https://github.com/gcovr/gcovr/issues/189
# Read on issues of using gcc in Windows
# gcc, cmake and ninja should be in PATH
test_script:
  - ps: $Env:PATH += ";C:\msys64\mingw64\bin"     
  # Install only dependencies, disable testing
  # Disable fetching dependencies
  - cmd: zef install --/test --test-depends --deps-only .
  # Run Build.rakumod as per zef docs
  - cmd: zef build . --verbose  
  # Test project in current directory            
  - cmd: zef test . --verbose 
