name: MacOS

on:
  push:
    branches:
      #- '*'
      - main
    tags-ignore:
      - '*'
  pull_request:

jobs:
  raku:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macOS-latest
        raku-version:
          - 'latest'          
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: Raku/setup-raku@v1
        with:
          raku-version: ${{ matrix.raku-version }}
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.12
      - name: Setup ninja
        uses: seanmiddleditch/gha-setup-ninja@master
      - name: Install Dependencies
        run: zef install --/test --test-depends --deps-only .
      - name: Run Tests
        run: |
          zef build . --verbose
          zef test . --verbose
